export const ACCOUNT = 'account';
export const LOGIN = 'login';
export const FORGOT_PASSWORD = 'forgot-password';
export const LAYOUT = 'admin';
export const HOME = 'dashboard';
export const MY_PROFILE='profile';
export const DIRECTORY='staff-directory';
export const ENTREPRENURSHIP ='entreprenurship';
export const BASIC = 'details';
export const PROFILE_PIC = 'profile-img';
export const QUALIFICATION = 'qualification';
export const SHIFT = 'shift';
export const CHANGE_PASSWORD = 'change-password';
export const APPRAISAL = 'appraisal';
export const EXPLORE = 'startup/add_pitch';
export const MY_PITCH = 'startup/my_pitch'
export const HOLIDAY_CALENDER ='holiday-calender';
export const JOB_OPENING ='refer-candidate/job_openings';
export const JOB_LIST= 'refer-candidate/list';
export const JOB_DETAILS ='refer-candidate/job_details'
export const POLICY_DOC='policy-documents';
export const REVIEW='monthly-review';
export const PERFORMANCE='monthly-review/my-performance';
export const INTERVIEW_LIST='interview/interview-list';
export const MY_FRESHER_TRAINING='freshers/my_trainings';
export const MY_TRAINING_DETAILS='freshers/training_details_trainee';
export const UPCOMING_TRAININGS = 'upcoming_trainings';
export const ONGOING_TRAININGS = 'ongoing_trainings';
export const MY_TRAININGS='my_trainings';
export const REQUEST_TRAININGS='requested_trainings'

